### ISSUE TITLE
Create Project Timeline & Deliverables

### ISSUE THREAD

**Issue by juliaparish** [jaws-bren/notebook#2]
# Project start/end
- [x] review assignment due dates to establish the project timeline
- [x] create a project schedule using Gantt chart format

# Project Budget
- [x] determine the client's project budget availability
- [x] establish contractor rate

# Establish deliverables
- [x] outline project deliverables
- [x] determine deliverable due dates
- [x] add a deliverable worksheet to Schedule sheet that includes due dates, budget, schedule, contractor rates

**Comment by wyliehampson** [comment]
Review assignment due dates.
![image](https://user-images.githubusercontent.com/88209438/142778113-ea83b5c2-3c2f-4515-8bbd-e5dcf838cdb4.png)

**Comment by wyliehampson** [comment]
Gnatt chart schedule
![image](https://user-images.githubusercontent.com/88209438/142778134-b8c18f95-ac2f-4fd0-a56f-78010147ade1.png)

**Comment by wyliehampson** [comment]
Clinet's budget (from the proposal)
![image](https://user-images.githubusercontent.com/88209438/142778174-be0b4bfa-24e2-489a-9285-ec6b337d25bb.png)

**Comment by wyliehampson** [comment]
Client's budget (from the rfp)
![image](https://user-images.githubusercontent.com/88209438/142778197-89f522ee-6fb5-4e41-b700-e7e537228c07.png)

**Comment by wyliehampson** [comment]
Contractor rate (from the proposal)
![image](https://user-images.githubusercontent.com/88209438/142778220-0e4bddc7-e011-4994-853a-1d8f31163c2c.png)

**Comment by wyliehampson** [comment]
Deliverables and their due dates
![image](https://user-images.githubusercontent.com/88209438/142778251-9da66d98-63d3-4038-9727-cd86f96102de.png)

**Comment by wyliehampson** [comment]
Deliverable excel sheet.
![image](https://user-images.githubusercontent.com/88209438/142778260-fa9d3da7-89c5-4e50-b121-c155a0e818aa.png)
