### ISSUE TITLE
Write Proposal

### ISSUE THREAD

**Issue by juliaparish** [jaws-bren/notebook#4]
Develop a proposal in response to RFP

- [x] create new Google document 
- [x] title proposal document to include team name
- [x] write overview paragraph by describing the project based on RFP details
- [x] add schedule of deliverables
- [x] add work schedule
- [x] add project costs and team rates
- [x] provide team details 
- [x] add table of contents

**Comment by hub-shale** [comment]
Final proposal google doc is available here: https://docs.google.com/document/d/1Qdk5H8urtGVeBb5BLIthDI6Lo0ZleDXZNOHcW9X0QDg/edit#heading=h.28dk612j0qdm
