### ISSUE TITLE
Create Binder for EDS220 presentation

### ISSUE THREAD

**Issue by juliaparish** [jaws-bren/notebook#6]
## Use Case Examples
- [x] write plain-text summary (1-2 paragraphs) of the use case example
- [x] create markdown and code blocks demonstrating how one walks through the desired use case example. 
- [x] insert discussion of the results and how they might be extended on further analysis

**Comment by wyliehampson** [comment]
Use case summary
![image](https://user-images.githubusercontent.com/88209438/142778457-656a9966-ed2d-4073-b7cc-507301161a9f.png)

**Comment by wyliehampson** [comment]
Markdown code
![image](https://user-images.githubusercontent.com/88209438/142778478-87f9d21d-e7c4-4dc6-8230-73e171d4f7e2.png)
![image](https://user-images.githubusercontent.com/88209438/142778483-be3f0940-0a31-4e06-a814-0deae9b6f605.png)

**Comment by wyliehampson** [comment]
Result discussion
![image](https://user-images.githubusercontent.com/88209438/142778509-90c627ab-332e-468c-b06e-74b906d093f1.png)
